baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "bulma-hugo-book"
disableKinds= ["taxonomy", "taxonomyTerm"]

# Book configuration
disablePathToLower =  true
enableGitInfo = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # (Optional, default 6) Set how many table of contents levels to be showed on page.
  # Use false to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
  # You can also specify this parameter per page in front matter
  BookToC= 3
  BookSection = '*'
  BookDateFormat= "Jan 2, 2006"